"use client";
import { reportDownloadUrl } from "@/lib/api";

export interface ReportViewerProps {
  runId: string;
  html: string;
  elapsedSec: number;
}

export function ReportViewer({ runId, html, elapsedSec }: ReportViewerProps) {
  return (
    <div className="card p-5">
      <div className="flex items-baseline justify-between mb-4">
        <span className="label-mono">report ready · {formatElapsed(elapsedSec)}</span>
        <a
          href={reportDownloadUrl(runId)}
          download={`outlier-report-${runId}.html`}
          className="btn-ghost text-[13px]"
        >
          ↓ download
        </a>
      </div>
      <iframe
        title="Outlier report"
        srcDoc={html}
        // sandbox: allow nothing scripty by default, since the report is static
        // HTML generated by our backend. If we ever want links to work in
        // future, add "allow-popups allow-popups-to-escape-sandbox".
        sandbox=""
        style={{
          width: "100%",
          height: "70vh",
          border: "1px solid var(--border)",
          borderRadius: "0.5rem",
          background: "#fff",
        }}
      />
    </div>
  );
}

function formatElapsed(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}
